### ISSUE TITLE
Uncaught TypeError in useFlag

### ISSUE THREAD

**Issue by kostyadubinin** [Unleash/proxy-client-vue#18]
### Describe the bug

Calling the `useFlag()` function in my project raises a TypeError:

```
useFlag('travel.landing')
```

## My configuration

```ts
// main.ts
import { createApp } from 'vue'
import App from './app/index.vue'
import { plugin as unleashPlugin } from '@unleash/proxy-client-vue'

const config = {
  url: 'http://localhost:4242/api/frontend',
  clientKey: 'default:development.unleash-insecure-frontend-api-token',
  refreshInterval: 15,
  appName: 'vue',
}

const app = createApp(App)
app.use(unleashPlugin, { config })
app.mount('#app')
```

```vue
<!-- TaskFooter.vue -->
<template>
  {{ enabled }}
</template>

<script lang="ts" setup>
import { useFlag } from '@unleash/proxy-client-vue'
const enabled = useFlag('travel.landing')
</script>
```

### Steps to reproduce the bug

I tried to reproduce it in a simple Vue app but it worked fine there. It raises the error only in my existing project.

### Logs, error output, etc.

```bash
Uncaught (in promise) TypeError: Cannot destructure property 'isEnabled' of 'inject(...)' as it is undefined.
    at useFlag (index.es.js:1581:11)
    at setup (TaskFooter.vue:40:17)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7044:29)
    at setupComponent (runtime-core.esm-bundler.js:7000:11)
    at mountComponent (runtime-core.esm-bundler.js:4921:13)
    at processComponent (runtime-core.esm-bundler.js:4896:17)
    at patch (runtime-core.esm-bundler.js:4488:21)
    at mountChildren (runtime-core.esm-bundler.js:4684:13)
    at processFragment (runtime-core.esm-bundler.js:4855:13)
```

### Screenshots

Backtrace:

<img width="1118" alt="Screenshot 2023-04-18 at 17 44 19" src="https://user-images.githubusercontent.com/2252576/232832182-58895fd9-6d17-423c-930e-1418c6542e48.png">

The line on which this error is raised:

<img width="1118" alt="Screenshot 2023-04-18 at 17 44 25" src="https://user-images.githubusercontent.com/2252576/232832202-195a5e14-d414-40d8-b7dc-839f4dcc25af.png">

How `useFlag()` is called:

<img width="1118" alt="Screenshot 2023-04-18 at 17 44 40" src="https://user-images.githubusercontent.com/2252576/232832214-9ef7b3e8-1710-4567-8ff8-9222cac34321.png">

### Unleash version

4.22.5

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Vuejs 3.2.30

**Comment by nunogois** [comment]
Hi @kostyadubinin, thanks for raising this issue.

Since you mentioned that this does not happen on a new, simple project, but only in your existing one, I would start by checking your dependency versions. E.g. you mentioned that you are using `vue: "3.2.30"` in your project - Is it viable to try bumping that to `vue: "^3.2.45"` to match the `proxy-client-vue` dependency and see whether that helps?

I also suggest having a look at https://github.com/nunogois/proxy-client-vue-demo - It's a simple demo that uses `proxy-client-vue`. This way you can check whether you still see the issue when running that project out of the box and what the differences may be between your project and this demo one.

Sorry if I can't be a bigger help at this point, but hopefully this will give you a starting point to help debug your issue.

**Comment by kostyadubinin** [comment]
Thanks for your reply @nunogois! I will take a look at the demo app and will check if I get the same error with a newer version of Vue.

**Comment by kostyadubinin** [comment]
@nunogois, I get the same error with Vue 3.2.45 but I found a workaround, I use [unleash-proxy-client-js](https://github.com/Unleash/unleash-proxy-client-js) instead of [proxy-client-vue](https://github.com/Unleash/proxy-client-vue) and it seems to be working fine.

**Comment by omnichronous** [comment]
I get the same erorr when I try to use the `useUnleashClient` composable in a plugin:

```ts
export default defineNuxtPlugin(async (nuxtApp) => {
  console.info(useUnleashClient())
})
```

```
Uncaught (in promise) TypeError: Cannot destructure property 'client' of 'inject(...)' as it is undefined.
    at useUnleashClient (@unleash_proxy-client-vue.js:1719:11)
    at watch.immediate (03.xxxxx.ts:108:20)
    at callWithErrorHandling (chunk-RAKT47ZN.js:1565:18)
    at callWithAsyncErrorHandling (chunk-RAKT47ZN.js:1573:17)
    at job (chunk-RAKT47ZN.js:3162:9)
    at callWithErrorHandling (chunk-RAKT47ZN.js:1565:32)
    at flushJobs (chunk-RAKT47ZN.js:1763:9)
```

I'm working around it by just importing the client manually, but it would be nice to be able to use the awesome composables. 🙏

**Comment by nunogois** [comment]
So, this usually happens when you're trying to use the `proxy-client-vue` methods without initializing your Unleash client first - There's no Unleash client context injected yet, that's why you get that error. It's trying to grab `client` from a value that is still `undefined`. I think improving the error is something we should consider doing at a later stage as it's not very intuitive as it is.

Can you double check that the error goes away if you [initialize](https://github.com/Unleash/proxy-client-vue#initialization) your Unleash client correctly before calling the associated methods?

I set something up that may help you: https://github.com/nunogois/proxy-client-vue-nuxt-plugin-demo

**Comment by omnichronous** [comment]
Thanks for looking into this @nunogois. 🙇 I think the problem might come from the fact that I'm using Nuxt (3). I'm initializing the Unleash client before calling `useUnleashClient()`, yes, but it happens in another Nuxt plugin. Even though they're set to load sequentially and I can confirm in other ways that the Unleash instance exists at the moment of calling `useUnleashClient()`, in the context of the Nuxt lifecycle it fails.

I think this happens because the [Nuxt context gets lost](https://nuxt.com/docs/api/composables/use-nuxt-app#runwithcontext) between the first plugin and the second, as
**(TLDR:) `useNuxtApp().runWithContext(() => useUnleashClient())` succeeds where `useUnleashClient()` fails**.

**Comment by nunogois** [comment]
No problem! Thank you for coming back with more detailed information.
That might be the case 🤔 It's been a while since I've used Nuxt extensively, so your insights are much appreciated.

I tried reproducing the issue by [adding a second plugin](https://github.com/nunogois/proxy-client-vue-nuxt-plugin-demo/tree/nuxt-post-unleash-plugin) in my demo app but I couldn't reproduce it: Everything seems to be working correctly. Can you please confirm that it also works for you? If not, could you please share a reproducible example?

Even if it works in Nuxt, the truth is `proxy-client-vue` was originally intended to be used in a frontend environment. That being said, if you identify something that we can improve to make your experience better with Nuxt or just in general, please let us know 🙂

**Comment by omnichronous** [comment]
@nunogois thank you for the demo 🙇 I did check it out. Over there you created a new client instance and used `provide` to pass it to the rest of the app. That's also what I did to make it work in my app, it was the composables like `useUnleashClient` that didn't work (when used in that plugin context).

Of course by Murphy's law when I tried that in your demo app it somehow worked 🤦‍♂️ but in my app I still encounter the `Cannot destructure property` errors. So just in case anyone else runs into these kinds of problems I'm leaving here the `runWithContext` approach which solved it for me.

> Even if it works in Nuxt, the truth is `proxy-client-vue` was originally intended to be used in a frontend environment. That being said, if you identify something that we can improve to make your experience better with Nuxt or just in general, please let us know 🙂

I appreciate that :) In fact I did just open a PR for a little addition to this SDK that would help me, and hopefully others, quite a lot. I'd really appreciate it if you gave it a look. Thanks again, cheers!
