### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by rwparris2** [Unleash/proxy-client-vue#21]
### Describe the feature request

Without a changelog, it is difficult to know if we are safe to upgrade.

**Comment by nunogois** [comment]
Thanks for opening this issue @rwparris2!

As `proxy-client-vue` still hasn't reached a minor version, having a look at the commit history may be your best bet for now: https://github.com/Unleash/proxy-client-vue/commits/main

If it helps, I made a new release on this repo with the aggregated changelog since v0.0.3:
https://github.com/Unleash/proxy-client-vue/releases/tag/v0.0.8

I hope this helps. We'll take your feedback into account for future releases.
